### PR TITLE
fix(modules/setup): return empty dict when netif JSON payload is empty

### LINKED ISSUE #149: setup: gathering of network interfaces seems to be unstable
##### SUMMARY

This requires further investigation, but local and CI tests fail quite often, usually succeeding after a re-run (or many). The error output seems to happen consistently in the step where the network interfaces info is gathered.

In at least one occasion, when it succeeded, that factoid was empty (`{}`).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

plugins/modules/setup.sh

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below
fatal: [openwrt_x86_64-25.12.0-rc5]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "{\"changed\":false,\"ansible_facts\":\n{ \"ansible_hostname\": \"openwrt_x86_64-25.12.0-rc5\", \"ansible_distribution\": \"OpenWrt\", \"ansible_distribution_major_version\": \"25\", \"ansible_distribution_release\": \"NA\", \"ansible_distribution_version\": \"25.12.0-rc5\", \"ansible_os_family\": \"OpenWrt\", \"ansible_pkg_mgr\": \"apk\", \"ansible_is_chroot\": false, \"ansible_date_time\": { \"date\": \"2026-02-22\", \"day\": \"22\", \"epoch\": \"1771724979\", \"epoch_int\": \"1771724979\", \"hour\": \"01\", \"iso8601\": \"2026-02-22T01:49:39Z\", \"iso8601_basic\": \"20260222T014939000000\", \"iso8601_basic_short\": \"20260222T014939\", \"iso8601_micro\": \"2026-02-22T01:49:39.000000Z\", \"minute\": \"49\", \"month\": \"02\", \"second\": \"39\", \"time\": \"01:49:39\", \"tz\": \"GMT\", \"tz_dst\": \"GMT\", \"tz_offset\": \"+0000\", \"weekday\": \"Sunday\", \"weekday_number\": \"0\", \"weeknumber\": \"07\", \"year\": \"2026\" } \n,\"openwrt_info\":{\n\t\"localtime\": 1771724979,\n\t\"uptime\": 1367151,\n\t\"load\": [\n\t\t258688,\n\t\t250816,\n\t\t211456\n\t],\n\t\"memory\": {\n\t\t\"total\": 16505151488,\n\t\t\"free\": 290779136,\n\t\t\"shared\": 4432789504,\n\t\t\"buffered\": 64008192,\n\t\t\"available\": 1475547136,\n\t\t\"cached\": 5462814720\n\t},\n\t\"root\": {\n\t\t\"total\": 209510172,\n\t\t\"free\": 81647744,\n\t\t\"used\": 127862428,\n\t\t\"avail\": 70932408\n\t},\n\t\"tmp\": {\n\t\t\"total\": 209510172,\n\t\t\"free\": 81647744,\n\t\t\"used\": 127862428,\n\t\t\"avail\": 70932408\n\t},\n\t\"swap\": {\n\t\t\"total\": 34359734272,\n\t\t\"free\": 22662541312\n\t}\n},\"openwrt_devices\":,\"openwrt_services\":{\n\t\"cron\": {\n\t\t\n\t},\n\t\"dnsmasq\": {\n\t\t\"instances\": {\n\t\t\t\"cfg01411c\": {\n\t\t\t\t\"running\": false,\n\t\t\t\t\"command\": [\n\t\t\t\t\t\"/usr/sbin/dnsmasq\",\n\t\t\t\t\t\"-C\",\n\t\t\t\t\t\"/var/etc/dnsmasq.conf.cfg01411c\",\n\t\t\t\t\t\"-k\",\n\t\t\t\t\t\"-x\",\n\t\t\t\t\t\"/var/run/dnsmasq/dnsmasq.cfg01411c.pid\"\n\t\t\t\t],\n\t\t\t\t\"term_timeout\": 5,\n\t\t\t\t\"exit_code\": 1,\n\t\t\t\t\"jail\": {\n\t\t\t\t\t\"name\": \"dnsmasq\",\n\t\t\t\t\t\"procfs\": false,\n\t\t\t\t\t\"sysfs\": false,\n\t\t\t\t\t\"ubus\": true,\n\t\t\t\t\t\"log\": true,\n\t\t\t\t\t\"ronly\": false,\n\t\t\t\t\t\"netns\": false,\n\t\t\t\t\t\"userns\": false,\n\t\t\t\t\t\"cgroupsns\": false,\n\t\t\t\t\t\"console\": false\n\t\t\t\t},\n\t\t\t\t\"mount\": {\n\t\t\t\t\t\"/bin/ubus\": \"0\",\n\t\t\t\t\t\"/etc/TZ\": \"0\",\n\t\t\t\t\t\"/etc/dnsmasq.conf\": \"0\",\n\t\t\t\t\t\"/etc/ethers\": \"0\",\n\t\t\t\t\t\"/etc/group\": \"0\",\n\t\t\t\t\t\"/etc/hosts\": \"0\",\n\t\t\t\t\t\"/etc/passwd\": \"0\",\n\t\t\t\t\t\"/tmp/dhcp.leases\": \"1\",\n\t\t\t\t\t\"/tmp/dnsmasq.cfg01411c.d\": \"0\",\n\t\t\t\t\t\"/tmp/hosts\": \"0\",\n\t\t\t\t\t\"/tmp/resolv.conf.d\": \"0\",\n\t\t\t\t\t\"/usr/bin/env\": \"0\",\n\t\t\t\t\t\"/usr/bin/jshn\": \"0\",\n\t\t\t\t\t\"/usr/lib/dnsmasq/dhcp-script.sh\": \"0\",\n\t\t\t\t\t\"/usr/share/dnsmasq/dhcpbogushostname.conf\": \"0\",\n\t\t\t\t\t\"/usr/share/dnsmasq/rfc6761.conf\": \"0\",\n\t\t\t\t\t\"/usr/share/dnsmasq/trust-anchors.conf\": \"0\",\n\t\t\t\t\t\"/usr/share/libubox/jshn.sh\": \"0\",\n\t\t\t\t\t\"/var/etc/dnsmasq.conf.cfg01411c\": \"0\",\n\t\t\t\t\t\"/var/run/dnsmasq/\": \"1\"\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t},\n\t\"dropbear\": {\n\t\t\"instances\": {\n\t\t\t\"instance1\": {\n\t\t\t\t\"running\": true,\n\t\t\t\t\"pid\": 715,\n\t\t\t\t\"command\": [\n\t\t\t\t\t\"/usr/sbin/dropbear\",\n\t\t\t\t\t\"-F\",\n\t\t\t\t\t\"-P\",\n\t\t\t\t\t\"/var/run/dropbear.main.pid\",\n\t\t\t\t\t\"-p\",\n\t\t\t\t\t\"22\",\n\t\t\t\t\t\"-K\",\n\t\t\t\t\t\"300\",\n\t\t\t\t\t\"-T\",\n\t\t\t\t\t\"3\"\n\t\t\t\t],\n\t\t\t\t\"term_timeout\": 5,\n\t\t\t\t\"data\": {\n\t\t\t\t\t\"mdns\": {\n\t\t\t\t\t\t\"ssh_22\": {\n\t\t\t\t\t\t\t\"service\": \"_ssh._tcp.local\",\n\t\t\t\t\t\t\t\"port\": 22,\n\t\t\t\t\t\t\t\"txt\": [\n\t\t\t\t\t\t\t\t\"daemon=dropbear\"\n\t\t\t\t\t\t\t]\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"respawn\": {\n\t\t\t\t\t\"threshold\": 3600,\n\t\t\t\t\t\"timeout\": 5,\n\t\t\t\t\t\"retry\": 5\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t},\n\t\"firewall\": {\n\t\t\n\t},\n\t\"gpio_switch\": {\n\t\t\n\t},\n\t\"log\": {\n\t\t\"instances\": {\n\t\t\t\"logd\": {\n\t\t\t\t\"running\": true,\n\t\t\t\t\"pid\": 422,\n\t\t\t\t\"command\": [\n\t\t\t\t\t\"/sbin/logd\",\n\t\t\t\t\t\"-S\",\n\t\t\t\t\t\"128\"\n\t\t\t\t],\n\t\t\t\t\"term_timeout\": 5,\n\t\t\t\t\"respawn\": {\n\t\t\t\t\t\"threshold\": 5,\n\t\t\t\t\t\"timeout\": 1,\n\t\t\t\t\t\"retry\": -1\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t},\n\t\"network\": {\n\t\t\"instances\": {\n\t\t\t\"instance1\": {\n\t\t\t\t\"running\": true,\n\t\t\t\t\"pid\": 833,\n\t\t\t\t\"command\": [\n\t\t\t\t\t\"/sbin/netifd\"\n\t\t\t\t],\n\t\t\t\t\"term_timeout\": 5,\n\t\t\t\t\"limits\": {\n\t\t\t\t\t\"core\": \"unlimited\"\n\t\t\t\t},\n\t\t\t\t\"respawn\": {\n\t\t\t\t\t\"threshold\": 3600,\n\t\t\t\t\t\"timeout\": 5,\n\t\t\t\t\t\"retry\": 5\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t},\n\t\"odhcpd\": {\n\t\t\"instances\": {\n\t\t\t\"instance1\": {\n\t\t\t\t\"running\": true,\n\t\t\t\t\"pid\": 950,\n\t\t\t\t\"command\": [\n\t\t\t\t\t\"/usr/sbin/odhcpd\"\n\t\t\t\t],\n\t\t\t\t\"term_timeout\": 5,\n\t\t\t\t\"respawn\": {\n\t\t\t\t\t\"threshold\": 3600,\n\t\t\t\t\t\"timeout\": 5,\n\t\t\t\t\t\"retry\": 5\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t},\n\t\"packet_steering\": {\n\t\t\n\t},\n\t\"rpcd\": {\n\t\t\"instances\": {\n\t\t\t\"instance1\": {\n\t\t\t\t\"running\": true,\n\t\t\t\t\"pid\": 476,\n\t\t\t\t\"command\": [\n\t\t\t\t\t\"/sbin/rpcd\",\n\t\t\t\t\t\"-s\",\n\t\t\t\t\t\"/var/run/ubus/ubus.sock\",\n\t\t\t\t\t\"-t\",\n\t\t\t\t\t\"30\"\n\t\t\t\t],\n\t\t\t\t\"term_timeout\": 5,\n\t\t\t\t\"respawn\": {\n\t\t\t\t\t\"threshold\": 3600,\n\t\t\t\t\t\"timeout\": 5,\n\t\t\t\t\t\"retry\": 5\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t},\n\t\"sysntpd\": {\n\t\t\"instances\": {\n\t\t\t\"instance1\": {\n\t\t\t\t\"running\": false,\n\t\t\t\t\"command\": [\n\t\t\t\t\t\"/usr/sbin/ntpd\",\n\t\t\t\t\t\"-n\",\n\t\t\t\t\t\"-N\",\n\t\t\t\t\t\"-S\",\n\t\t\t\t\t\"/usr/sbin/ntpd-hotplug\",\n\t\t\t\t\t\"-p\",\n\t\t\t\t\t\"0.openwrt.pool.ntp.org\",\n\t\t\t\t\t\"-p\",\n\t\t\t\t\t\"1.openwrt.pool.ntp.org\",\n\t\t\t\t\t\"-p\",\n\t\t\t\t\t\"2.openwrt.pool.ntp.org\",\n\t\t\t\t\t\"-p\",\n\t\t\t\t\t\"3.openwrt.pool.ntp.org\"\n\t\t\t\t],\n\t\t\t\t\"term_timeout\": 5,\n\t\t\t\t\"exit_code\": 1,\n\t\t\t\t\"respawn\": {\n\t\t\t\t\t\"threshold\": 3600,\n\t\t\t\t\t\"timeout\": 5,\n\t\t\t\t\t\"retry\": 5\n\t\t\t\t},\n\t\t\t\t\"no_new_privs\": true,\n\t\t\t\t\"capabilities\": \"/etc/capabilities/ntpd.json\",\n\t\t\t\t\"user\": \"ntp\",\n\t\t\t\t\"group\": \"ntp\",\n\t\t\t\t\"jail\": {\n\t\t\t\t\t\"name\": \"ntpd\",\n\t\t\t\t\t\"procfs\": false,\n\t\t\t\t\t\"sysfs\": false,\n\t\t\t\t\t\"ubus\": true,\n\t\t\t\t\t\"log\": false,\n\t\t\t\t\t\"ronly\": false,\n\t\t\t\t\t\"netns\": false,\n\t\t\t\t\t\"userns\": false,\n\t\t\t\t\t\"cgroupsns\": false,\n\t\t\t\t\t\"console\": false\n\t\t\t\t},\n\t\t\t\t\"mount\": {\n\t\t\t\t\t\"/bin/ubus\": \"0\",\n\t\t\t\t\t\"/usr/bin/env\": \"0\",\n\t\t\t\t\t\"/usr/bin/jshn\": \"0\",\n\t\t\t\t\t\"/usr/sbin/ntpd-hotplug\": \"0\",\n\t\t\t\t\t\"/usr/share/libubox/jshn.sh\": \"0\"\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t},\n\t\"system\": {\n\t\t\n\t},\n\t\"ubus\": {\n\t\t\"instances\": {\n\t\t\t\"instance1\": {\n\t\t\t\t\"running\": true,\n\t\t\t\t\"pid\": 91,\n\t\t\t\t\"command\": [\n\t\t\t\t\t\"/sbin/ubusd\"\n\t\t\t\t],\n\t\t\t\t\"term_timeout\": 5,\n\t\t\t\t\"respawn\": {\n\t\t\t\t\t\"threshold\": 3600,\n\t\t\t\t\t\"timeout\": 1,\n\t\t\t\t\t\"retry\": 0\n\t\t\t\t},\n\t\t\t\t\"user\": \"ubus\",\n\t\t\t\t\"group\": \"ubus\"\n\t\t\t}\n\t\t}\n\t},\n\t\"ucitrack\": {\n\t\t\n\t},\n\t\"uhttpd\": {\n\t\t\"instances\": {\n\t\t\t\"instance1\": {\n\t\t\t\t\"running\": true,\n\t\t\t\t\"pid\": 1075,\n\t\t\t\t\"command\": [\n\t\t\t\t\t\"/usr/sbin/uhttpd\",\n\t\t\t\t\t\"-f\",\n\t\t\t\t\t\"-h\",\n\t\t\t\t\t\"/www\",\n\t\t\t\t\t\"-r\",\n\t\t\t\t\t\"OpenWrt\",\n\t\t\t\t\t\"-x\",\n\t\t\t\t\t\"/cgi-bin\",\n\t\t\t\t\t\"-u\",\n\t\t\t\t\t\"/ubus\",\n\t\t\t\t\t\"-t\",\n\t\t\t\t\t\"60\",\n\t\t\t\t\t\"-T\",\n\t\t\t\t\t\"30\",\n\t\t\t\t\t\"-k\",\n\t\t\t\t\t\"20\",\n\t\t\t\t\t\"-A\",\n\t\t\t\t\t\"1\",\n\t\t\t\t\t\"-n\",\n\t\t\t\t\t\"3\",\n\t\t\t\t\t\"-N\",\n\t\t\t\t\t\"100\",\n\t\t\t\t\t\"-R\",\n\t\t\t\t\t\"-p\",\n\t\t\t\t\t\"0.0.0.0:80\",\n\t\t\t\t\t\"-p\",\n\t\t\t\t\t\"[::]:80\",\n\t\t\t\t\t\"-C\",\n\t\t\t\t\t\"/etc/uhttpd.crt\",\n\t\t\t\t\t\"-K\",\n\t\t\t\t\t\"/etc/uhttpd.key\",\n\t\t\t\t\t\"-s\",\n\t\t\t\t\t\"0.0.0.0:443\",\n\t\t\t\t\t\"-s\",\n\t\t\t\t\t\"[::]:443\"\n\t\t\t\t],\n\t\t\t\t\"term_timeout\": 5,\n\t\t\t\t\"respawn\": {\n\t\t\t\t\t\"threshold\": 3600,\n\t\t\t\t\t\"timeout\": 5,\n\t\t\t\t\t\"retry\": 5\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t},\n\t\"urandom_seed\": {\n\t\t\"instances\": {\n\t\t\t\"urandom_seed\": {\n\t\t\t\t\"running\": false,\n\t\t\t\t\"command\": [\n\t\t\t\t\t\"/sbin/urandom_seed\"\n\t\t\t\t],\n\t\t\t\t\"term_timeout\": 5,\n\t\t\t\t\"exit_code\": 0\n\t\t\t}\n\t\t}\n\t},\n\t\"urngd\": {\n\t\t\"instances\": {\n\t\t\t\"instance1\": {\n\t\t\t\t\"running\": true,\n\t\t\t\t\"pid\": 125,\n\t\t\t\t\"command\": [\n\t\t\t\t\t\"/sbin/urngd\"\n\t\t\t\t],\n\t\t\t\t\"term_timeout\": 5\n\t\t\t}\n\t\t}\n\t}\n},\"openwrt_board\":{\n\t\"kernel\": \"6.11.0-1016-lowlatency\",\n\t\"hostname\": \"openwrt_x86_64-25.12.0-rc5\",\n\t\"system\": \"Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz\",\n\t\"model\": \"LENOVO 20HE002DAU\",\n\t\"board_name\": \"lenovo-20he002dau\",\n\t\"release\": {\n\t\t\"distribution\": \"OpenWrt\",\n\t\t\"version\": \"25.12.0-rc5\",\n\t\t\"firmware_url\": \"https://downloads.openwrt.org/\",\n\t\t\"revision\": \"r32673-482ba7230a\",\n\t\t\"target\": \"x86/64\",\n\t\t\"description\": \"OpenWrt 25.12.0-rc5 r32673-482ba7230a\",\n\t\t\"builddate\": \"1771363837\"\n\t}\n},\"openwrt_interfaces\":{\n\"lan\":,\"loopback\":}}}\n", "msg": "Module result deserialization failed: Expecting value: line 35 column 21 (char 1369)", "rc": 0}
```

Note the part at the very end (removing extraneous escapes):
```
"openwrt_interfaces":{\n"lan":,"loopback":}}}\n
```
That JSON excerpt is clearly invalid - keys `lan` and `loopback` have no value.

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY

As shown in #149 the setup module sometimes fails when retrieving the information about the network interfaces.

This PR makes the module more resilient, returning an empty dict when it fails to obtain the information from `ubus`, instead of generating invalid JSON content.

Fixes #149 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

setup

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

File: plugins/modules/setup.sh [hunk 1]
```diff
@@ -9,7 +9,11 @@ add_ubus_fact() {
     set -- ${1//!/ }
     ubus list "$2" > /dev/null 2>&1 || return
     local json="$($ubus call "$2" "$3" 2>/dev/null)"
-    echo -n "$delimiter\"$1\":$json"
+    if [ -n "$json" ]; then
+        echo -n "$delimiter\"$1\":$json"
+    else
+        echo -n "$delimiter\"$1\":{}"
+    fi
```
Comment (Jonny007-MKD) [inline plugins/modules/setup.sh]: nit: to make it clearer that we default to `"{}"` in case of empty and not duplicate the output "logic":

```suggestion
    if [ -z "$json" ]; then
        json="{}"
    fi
    echo -n "$delimiter\"$1\":$json"
```
